---
# Install the collections using:
# ansible-galaxy collection install -p collections -r ./requirements/collections.yml
collections:
  - name: nixknight.docker
    type: git
    source: "git+https://github.com/NIXKnight/Ansible-Collections.git#/collections/nixknight/docker,6e9e1fc2f2dff6e26cca744727df3a067c508be5"
  - name: nixknight.opentofu
    type: git
    source: "git+https://github.com/NIXKnight/Ansible-Collections.git#/collections/nixknight/opentofu,6e9e1fc2f2dff6e26cca744727df3a067c508be5"
  - name: nixknight.general
    type: git
    source: "git+https://github.com/NIXKnight/Ansible-Collections.git#/collections/nixknight/general,6e9e1fc2f2dff6e26cca744727df3a067c508be5"
