---
- name: Create/Update PostgreSQL Databases and Users Privileges
  hosts: data_services
  gather_facts: yes
  become: True
  vars_files:
    - "{{ ansible_config_file | dirname }}/../../Home-Ops-Internal/ansible/Linux-Firewall-Gateway/data-services.yml"
  roles:
    - pgsql_dbs_users
