---
- name: Setup/Update Monitoring
  hosts: monitoring
  gather_facts: yes
  become: True
  collections:
    - nixknight.docker
  vars_files:
  - "{{ ansible_config_file | dirname }}/../../Home-Ops-Internal/ansible/inventories/group_vars/firewall.yml"
  - "{{ ansible_config_file | dirname }}/../../Home-Ops-Internal/ansible/inventories/group_vars/powerdns.yml"
  - "{{ ansible_config_file | dirname }}/../../Home-Ops-Internal/ansible/Linux-Firewall-Gateway/acme.yml"
  - "{{ ansible_config_file | dirname }}/../../Home-Ops-Internal/ansible/Linux-Firewall-Gateway/monitoring.yml"
  roles:
    - role: docker-compose-service
      DOCKER_COMPOSE_SERVICE_NAME: "{{ MONITORING_SERVICE_NAME }}"
      DOCKER_COMPOSE_SERVICE_SYSTEMD_DESCRIPTION: "{{ MONITORING_SERVICE_SYSTEMD_DESCRIPTION }}"
      DOCKER_COMPOSE_SERVICE_SYSTEMD_REQUIRES: "{{ MONITORING_SERVICE_SYSTEMD_REQUIRES }}"
      DOCKER_COMPOSE_SERVICE_SYSTEMD_AFTER: "{{ MONITORING_SERVICE_SYSTEMD_AFTER }}"
      DOCKER_COMPOSE_SERVICE_SYSTEMD_FILE: "{{ MONITORING_SERVICE_SYSTEMD_FILE }}"
      DOCKER_COMPOSE_SERVICE_IMAGES: "{{ MONITORING_SERVICE_IMAGES }}"
      DOCKER_COMPOSE_SERVICE_COMPOSE_PATH: "{{ MONITORING_SERVICE_COMPOSE_PATH }}"
      DOCKER_COMPOSE_SERVICE_MANIFEST: "{{ MONITORING_SERVICE_MANIFEST }}"
      DOCKER_COMPOSE_SERVICE_CONFIG_PATH: "{{ MONITORING_COMPOSE_SERVICE_CONFIG_PATH }}"
      DOCKER_COMPOSE_SERVICE_TEMPLATES: "{{ MONITORING_COMPOSE_SERVICE_TEMPLATES }}"
      DOCKER_COMPOSE_SERVICE_FILES: "{{ MONITORING_COMPOSE_SERVICE_FILES }}"
      DOCKER_COMPOSE_SERVICE_SET_GROUP_ID: true
