---
- name: Run Common Roles
  hosts: all
  gather_facts: yes
  become: True
  collections:
    - nixknight.general
  vars_files:
  - "{{ playbook_dir }}/extravars/common.yml"
  roles:
    - role: linux-common
    - role: motd
